name: Run SnapMock

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  snapmock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Check current directory
        run: |
          echo "Current Directory:"
          pwd  # Print the current directory


      - name: Run SnapMock
        uses: Programming-Sai/SnapMock@main  # This will automatically pull the latest v1 commit
        with:
          url: "https://programming-sai.github.io/Fertilizer-Recommendation-System/"
          devices: "laptop"
          output: "snapshots"

      - name: Debug snapshot output
        run: |
          echo "Snapshot output contents:"
          ls -R ./snapshots || echo "No snapshots directory found"

      - name: Move SnapMock screenshots to workspace
        run: |
          mkdir -p ${{ github.workspace }}/snapshots
          cp -r ${{ github.action_path }}/snapshots/* ${{ github.workspace }}/snapshots/

      - name: Deploy to Custom Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./snapshots
          publish_branch: snapmock-output  # User-specified branch
          commit_message: "Update SnapMock screenshots [skip ci]"
        env:
          GIT_AUTHOR_NAME: "SnapMock Bot"
          GIT_AUTHOR_EMAIL: "snapmock@users.noreply.github.com"
